"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from oscar.defaults import *

location = lambda x: os.path.join(
    os.path.dirname(os.path.realpath(__file__)), x)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1y@!pn4(zjthyhugm&2b0zp^gu6^(k9bmrcwgh&=c+pwqk8-1$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
 
    
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',

 'django.contrib.sites',
 'django.contrib.flatpages',

 'oscar.config.Shop',
 
 'oscar.apps.analytics.apps.AnalyticsConfig',
 'oscar.apps.checkout.apps.CheckoutConfig',
 'oscar.apps.address.apps.AddressConfig',
 'oscar.apps.shipping.apps.ShippingConfig',
 'oscar.apps.catalogue.apps.CatalogueConfig',
 'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
 'oscar.apps.communication.apps.CommunicationConfig',
 
 'oscar.apps.partner.apps.PartnerConfig',
 'oscar.apps.basket.apps.BasketConfig',
 'oscar.apps.payment.apps.PaymentConfig',
 'oscar.apps.offer.apps.OfferConfig',
 'oscar.apps.order.apps.OrderConfig',
 'oscar.apps.customer.apps.CustomerConfig',
 'oscar.apps.search.apps.SearchConfig',
 'oscar.apps.voucher.apps.VoucherConfig',
 'oscar.apps.wishlists.apps.WishlistsConfig',
 'oscar.apps.dashboard.apps.DashboardConfig',
 'oscar.apps.dashboard.reports.apps.ReportsDashboardConfig',
 'oscar.apps.dashboard.users.apps.UsersDashboardConfig',
 'oscar.apps.dashboard.orders.apps.OrdersDashboardConfig',
 'oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig',
 'oscar.apps.dashboard.offers.apps.OffersDashboardConfig',
 'oscar.apps.dashboard.partners.apps.PartnersDashboardConfig',
 'oscar.apps.dashboard.pages.apps.PagesDashboardConfig',
 'oscar.apps.dashboard.ranges.apps.RangesDashboardConfig',
 'oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig',
 'oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig',
 'oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig',
 'oscar.apps.dashboard.shipping.apps.ShippingDashboardConfig',

 # 3rd-party apps that oscar depends on
 'widget_tweaks',
 'haystack',
 'treebeard',
 'sorl.thumbnail', # Default thumbnail backend, can be replaced
 'django_tables2',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oscar.apps.basket.middleware.BasketMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'config.urls'
print(os.path.join(BASE_DIR, 'templates'))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR / 'config' / 'templates'],
        'DIRS': [os.path.join(BASE_DIR, 'config/templates')], 
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'oscar.apps.search.context_processors.search_form',
                'oscar.apps.checkout.context_processors.checkout',
                'oscar.apps.communication.notifications.context_processors.notifications',
                'oscar.core.context_processors.metadata',
            ],
        },
    },
]



WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "stroymir",
        "USER": "stroymir",
        "PASSWORD": "stroymir",
        "HOST": "localhost", 
        "PORT": "5432",
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',  # Измените на django_redis
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',  # Добавьте django_redis
        }
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# MEDIA_ROOT = location("public/media")

# # URL that handles the media served from MEDIA_ROOT. Make sure to use a
# # trailing slash if there is a path component (optional in other cases).
# # Examples: "http://media.lawrence.com", "http://example.com/media/"
# MEDIA_URL = '/media/'

# STATIC_URL = '/static/'
# STATIC_ROOT = location('public/static')
# STATICFILES_DIRS = [
#     BASE_DIR / 'config' / 'static',  # Указываем путь к вашим статическим файлам
# ]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')

# Дополнительные настройки для статических файлов
STATICFILES_DIRS = [
    BASE_DIR / 'config' / 'static',
]
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# STATIC_URL = '/static/'
# STATIC_ROOT = location('public/static')
# STATICFILES_DIRS = (
#     location('static/'),
# )

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
 'oscar.apps.customer.auth_backends.EmailBackend',
 'django.contrib.auth.backends.ModelBackend',
)
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# HAYSTACK_CONNECTIONS = {
#     'default': {
#         'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
#         'URL': 'http://localhost:8983/solr/mycore/',
#         'INCLUDE_SPELLING': True,
#     },
# }


# Here's a sample Haystack config for Solr 6.x (which is recommended)
# HAYSTACK_CONNECTIONS = {
#     'default': {
#         'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
#         'URL': 'http://127.0.0.1:8983/solr/sandbox',
#         'ADMIN_URL': 'http://127.0.0.1:8983/solr/admin/cores',
#         'INCLUDE_SPELLING': True,
#     }
# }
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': location('whoosh_index'),
        'INCLUDE_SPELLING': True,
    },
}

# HAYSTACK_CONNECTIONS = {
#     'default': {
#         'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
#     },
# }

OSCAR_DEFAULT_CURRENCY = 'RUB'
OSCAR_ALLOW_ANON_CHECKOUT = True
# OSCAR_PRODUCT_TITLE_MAX_LENGTH = 10