
services:
  db:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: stroymir
      POSTGRES_USER: stroymir
      POSTGRES_PASSWORD: stroymir # Пароль задаем здесь, как переменную окружения
      POSTGRES_HOST_AUTH_METHOD: trust # Разрешаем подключения
      POSTGRES_HOST: 0.0.0.0 # Слушаем все интерфейсы
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Стандартный порт
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
  pgadmin:
    image: dpage/pgadmin4:8.6
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # solr:
  #   image: solr:10.0.0
  #   container_name: solr
  #   restart: always
  #   ports:
  #     - "8983:8983"
  #   volumes:
  #     - ./solr-data:/var/solr/data:z
    # command: precreate-core stroymir
    
  # solr:
  #   image: docker.io/library/solr:6.6.6
  #   platform: linux/amd64
  #   container_name: solr
  #   restart: unless-stopped
  #   ports:
  #     - "8983:8983"
  #   volumes:
  #     - ./solr-data:/var/solr/data
  #   environment:
  #     SOLR_HOME: /var/solr/data
  #     SOLR_MODE: standalone
  #     SOLR_DEFAULT_CONFIG: data_driven_schema_configs
  #   command: bash -c "cp /opt/solr/server/solr/solr.xml /var/solr/data/ && solr-precreate oscar"


  # solr:
  #     image: solr:8.11.2
  #     platform: linux/amd64
  #     container_name: solr
  #     restart: unless-stopped
  #     ports:
  #       - "8983:8983"
  #     volumes:
  #       - ./solr-data:/var/solr/data
  #     environment:
  #       SOLR_HOME: /var/solr/data
  #       SOLR_MODE: standalone
  #     command: solr-precreate oscar

  
  solr:
    image: solr:8.11.2
    
    container_name: solr
    ports:
      - "8983:8983"

    # 👉 Правильно настраиваем монтирование
    volumes:
      - ./oscar_config:/opt/solr-8.11.2/server/solr/configsets/oscar-config
      - ./solr_data:/opt/solr-8.11.2/server/solr

    # 👉 Только heap, остальное не трогаем
    environment:
      SOLR_HEAP: "512m"

    # 👉 Запускаем только сервер
    # command: solr-precreate oscar_stroymir oscar-config
    command: solr-precreate oscar_stroymir /opt/solr/server/solr/configsets/oscar-config

  # solr:
  #   image: solr:10.0.0
  #   container_name: solr
  #   restart: always
  #   ports:
  #     - "8983:8983"
  #   volumes:
  #     # - ./solr-configsets:/opt/solr/server/solr/cloud/example-cloud/configsets
  #     # - ./solr-data:/var/solr/data
      
  #     - ./solr-configsets:/opt/solr/server/solr/configsets
  #     - ./solr-data:/var/solr/data
  #   environment:
  #     - SOLR_MODE=cloud

  # solr:
  #   image: solr:10.0.0
  #   container_name: solr
  #   restart: always
  #   ports:
  #     - "8983:8983"
  #   # command:
  #   # - precreate_collection
  #   # - stroymir
  #   # - "1"  # Количество шардов
  #   # - "1"  # Количество реплик
  #   # - "-c"  # Ключ для конфига
  #   # - "_default"  # Имя конфига
  #   environment:
  #     - SOLR_JAVA_MEM=-Xms512m -Xmx2g
  #     - SOLR_OPTS=-Dsolr.allowUnsafeLocalContext=true
  #   volumes:
  #     - ./solr-data:/var/solr/data:z
  #     - ./solr-logs:/var/solr/logs:z
  #     # - ./solr-configsets:/var/solr/server/solr/configsets:z # <-- Правильный путь
  #   # command: precreate-core stroymir -c data_driven_schema_configs

  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8983/solr/admin/info/system"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   mem_limit: 4g
  #   mem_reservation: 2g
  #   networks:
  #     - solr-network

networks:
  solr-network:
    driver: bridge


volumes:
  pgdata: {}
  redisdata: {}
  pgadmin-data: {}
  solr_data: {}
    